name: Build

on: [push, pull_request, workflow_call]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Replace version in app.json
              if: startsWith(github.ref, 'refs/tags/v')
              run: |
                  sed -i "s/\"version\": \"0.0.1\"/\"version\": \"${GITHUB_REF##*/v}\"/" app.json

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.1.2
              with:
                  node-version: "12"

            - name: Install dependencies
              run: npm i

            - name: Install Rocket.Chat Apps cli
              run: npm i -g @rocket.chat/apps-cli

            - name: Bundle App
              run: rc-apps package

            - uses: actions/upload-artifact@v2
              with:
                  name: build
                  path: ./dist/*.zip
                  if-no-files-found: error
