name: Release

on:
    push:
        tags:
            - v**

jobs:
    build:
        uses: sveatlo/Rocket.Chat.Reminder/.github/workflows/build.yml@master
    release:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/download-artifact@v2
              with:
                  name: build
            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  prerelease: false
                  files: |
                      *.zip
